config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  post 'kids/:id/', to: 'kids#add', as: "add_word"
  # ask about where this route should be to avoid confusion with kids#destroy
  # need help with route - not connecting
  delete 'kids/:id/:word', to: 'kids#remove', as: "remove_word"
  devise_for :users
  root to: 'pages#home'
  get 'pages/support'
  get 'pages/privacy_policy'

  resources :dashboards, only: :index
  resources :kids do
    resources :dictionaries do
      resources :suggestions
      # might make sense to have the suggestions on the dictionary page
      # and then when selected immediately pushed into the dictionary words array
      # so i nested it here - but can be changed depending on our page layout
    end
  end
  resources :articles, only: %i[index show]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :pages, only: %i[create]
      resources :statistics, only: %i[create]
    end
  end
end

app/models/kid.rb
class Kid < ApplicationRecord
  acts_as_taggable_on :tags
  belongs_to :user
  belongs_to :dictionary
  has_many :statistics

  validates :first_name, :last_name, :birthday, presence: true
  has_one_attached :photo
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: %i[show edit update destroy add remove]

  def show
    authorize @kid
    @dictionary = @kid.dictionary
    @words = @dictionary.words
  end

  def create
    @kid = Kid.new(kid_params)
    authorize @kid
    @kid.dictionary = Dictionary.new
    @kid.user = current_user
    if @kid.save
      redirect_to dashboards_path
    else
      render partial: "kids/new"
      # flash.now[:alert] = "Sorry, child wasn't added"
      # render "dashboards/index"
    end
  end

  def new
    @kid = Kid.new
    authorize @kid
  end

  def edit
    authorize @kid
  end

  def update
    authorize @kid
    @kid.update(kid_params)
    if @kid.save
      redirect_to kid_path(@kid)
    else
      flash[:alert] = "Details were not updated"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    authorize @kid
    @kid.destroy
    flash[:remove] = "Successfully deleted"

    redirect_to dashboards_path
  end

  def add
    authorize @kid
    word = params[:word]
    dictionary = @kid.dictionary
    words = dictionary.words
    if words.include?(word)
      redirect_to kid_path(@kid), flash: { alert: "Word is already being blocked!" }
    elsif word.empty?
      redirect_to kid_path(@kid), flash: { alert: "Please enter in a word" }
    else
      words << word
      dictionary.save

      redirect_to kid_path(@kid)
    end
  end

  def remove
    # will refactor later if I  have time to a dictionary controller?
    word = params[:word]
    dictionary = @kid.dictionary
    dictionary.words.delete(word)
    dictionary.save
    authorize @kid
    redirect_to kid_path(@kid)
    # raise
  end

  private

  def kid_params
    params.require(:kid).permit(:first_name, :last_name, :birthday, :age, :ethnicity, :sexual_orientation, :gender_identity, :photo)
  end

  def word_params
    params.require(:kid).permit(:word)
  end

  def set_kid
    @kid = Kid.find(params[:id])
  end
end

app/views/kids/_edit.html.erb
<div class="container">
      <h2 class="mt-4">Update <%= "#{@kid.first_name}" %>'s Details</h2>
      <p>
        <em>All the information collected will be used only to help curate
        a user experience matching the unique and amazing qualities of your child.
        It will never be used for anything else.</em>
      </p>
      <%= render 'kids/form', kid: @kid %>
      <%= link_to 'Cancel', kid_path(@kid), class: 'btn btn-outline-danger float-left' %>
</div>

app/views/kids/_form.html.erb
<%= simple_form_for (kid) do |f| %>
  <%= f.input :first_name, placeholder: "First Name", label: "Name"%>
  <%= f.input :last_name, placeholder: "Last Name",label: false%>
  <%= f.input :birthday, as: :date, html5: true, :input_html => { id: "dob"}%>
  <%# will update later to automatically calculate age based off birthday? %>
  <%= f.input :age, as: :integer, as: :hidden, :input_html => { id: "calc_age"} %>
  <%= f.input :ethnicity,
      collection: ["Caucasian", "African Descent", "Hispanic Pacific Islander",
                "American Indian or Alaska Native", "Asian", "Multi-ethnic" ], prompt: "Ethnicity", label: false, input_html: { class: 'select2', style:"width: 100%" }  %>

  <%= f.input :sexual_orientation,
      collection: %w[Heterosexual Bisexual Pansexual Gay Lesbian Asexual ], prompt: "Sexual Orientation", label: false, input_html: { class: 'select2', style:"width: 100%" }  %>
  <%= f.input :gender_identity, collection: %w[Male Female Transgender Other], prompt: "Gender Identity", label: false, input_html: { class: 'select2', style:"width: 100%" }  %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Confirm", class: "btn btn-outline-primary float-right" %>
<% end %>

app/views/kids/_new.html.erb
<div class="container">
      <h2 class="mt-4">Add a New Child</h2>
      <p>
        <em>All the information collected will be used only to help curate
        a user experience matching the unique and amazing qualities of your child.
        It will never be used for anything else.</em>
      </p>
      <%= render 'kids/form', kid: @kid %>
      <%= link_to 'Cancel', dashboards_path, class: 'btn btn-outline-danger float-left' %>
</div>

app/views/kids/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <h2 class="mt-4">Add a New Child</h2>
      <p>
        <em>All the information collected will be used only to help curate
        a user experience matching the unique and amazing qualities of your child.
        It will never be used for anything else.</em>
      </p>
      <%= render 'form', kid: @kid %>
      <%= link_to 'Cancel', dashboards_path, class: 'btn btn-outline-secondary m-3 float-right' %>
    </div>
  </div>
</div>

app/views/kids/show.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/sidebar' %>
<div class="dash-cont">
  <h1 class="border-bottom mt-5 ml-3" id="header-center"><%= "#{@kid.first_name} #{@kid.last_name}'s Information" %></h1>
  <div class="row justify-content-around">
    <div class="col-lg-7 col-12 mt-5 dictionary-card white-card text-center">
      <h3><%= "#{@kid.first_name}'s Blocked Word List" %></h3>
      <% if @dictionary.words.empty? %>
        <p>No blocked words yet.</p>
      <% else %>
        <% @words.each do |word| %>
        <li class="word-list"><%= word %>
          <%= link_to 'x', remove_word_path(@kid, word), method: :delete, class: "remove-word" %>
        </li>
        <% end %>
      <% end %>
      <%= form_with url: add_word_path, method: :post, class: "input-group mb-3 mt-2" do |form| %>
        <%= form.text_field :word, placeholder: "Add a word to block", class: "form-control" %>
        <%= form.submit "Add", class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
    <div class="white-card mt-5 col-lg-4 col-12 text-center">
      <h3><%= "#{@kid.first_name}'s Detail's" %></h3>
      <p>Devices: Macbook Pro, iPhone SE</p>
      <%= link_to "Update #{@kid.first_name}'s Details", edit_kid_path(@kid), class: "btn btn-outline-secondary mt-3 mb-3", data: {toggle: "modal", target: "#editKidModal"} %>
    </div>
    <div class="white-card">
      <p>Amount of scanned tweets</p>
      <%= line_chart Statistic.where(kid_id: @kid.id).group_by_day(:created_at).count, label: " scanned tweets", min:0, max:400, curve: false %>
    </div>
    <div class="white-card">
      <p>Amount of blocked tweets</p>
      <%= pie_chart Statistic.where(kid_id: @kid.id).where(tone: %i[4 5 6 7]).order(:tone).group(:tone).count, colors: ["#9b2226", "#bb3e03", "#ca6702", "#ee9b00"], donut: true, dataset: {cutout: "40%"} %>
    </div>
    <div class="white-card">
      <p>Types of scanned tweets</p>
      <%= pie_chart Statistic.where(kid_id: @kid.id).where(tone: %i[0 1 2 3 4 5 6 7]).order(:tone).group(:tone).count, colors:["#005f73", "#0a9396", "#0096c7", "#94d2bd", "#9b2226", "#bb3e03", "#ca6702", "#ee9b00"], donut: true, dataset: {cutout: "40%"} %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editKidModal" tabindex="-1" role="dialog" aria-labelledby="editKidModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'kids/edit', kid: @kid %>
      </div>
    </div>
  </div>
</div>