config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  post 'kids/:id/', to: 'kids#add', as: "add_word"
  # ask about where this route should be to avoid confusion with kids#destroy
  # need help with route - not connecting
  delete 'kids/:id/:word', to: 'kids#remove', as: "remove_word"
  devise_for :users
  root to: 'pages#home'
  get 'pages/support'
  get 'pages/privacy_policy'

  resources :dashboards, only: :index
  resources :kids do
    resources :dictionaries do
      resources :suggestions
      # might make sense to have the suggestions on the dictionary page
      # and then when selected immediately pushed into the dictionary words array
      # so i nested it here - but can be changed depending on our page layout
    end
  end
  resources :articles, only: %i[index show]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :pages, only: %i[create]
      resources :statistics, only: %i[create]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section class="footer">

  <div class="title-text-footer">
    <div class="title-text-footer">
      <h1>CHIRP AT US!</h1>
    </div>
  </div>
  <div class="footer-row">
    <div class="footer-left">
      <h3>Learn More.</h3>
      <p>Chirpy is a project that has been put together by 4 passionate individuals all residing in Tokyo. It was born from the desire to protect our loved ones from harmful and toxic content on the internet.</p>
    </div>
    <div class="footer-right">
      <h3>Get In Touch.</h3>
      <p>chirpyapp@gmail.com</p>
      <p>080-2126-0278</p>
    </div>
  </div>

  <div class="social-links">
    <a href="https://www.facebook.com/thatkbguy" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.instagram.com/kb_benice/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://twitter.com/ChirpyAppTokyo" target="_blank"><i class="fab fa-twitter"></i></a>
    <%# <i class="fab fa-youtube"></i> %>
    <p>&copy 2022 Team Chirpy</p>
  </div>

</section>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav">
      <% if user_signed_in? %>
        <%= link_to "Dashboard", dashboards_path, class: "dropdown-item nav-link ml-2" %>
        <%= link_to "Articles", articles_path, class: "dropdown-item nav-link ml-2" %>
        <%= link_to "Support", pages_support_path, class: "dropdown-item nav-link ml-2" %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item nav-link sign-out ml-2" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
  <div class="sidebar">
    <%# <img src="/image/chirpylogo.jpeg" alt="chirpy logo"> %>
    <%# logo path not working? %>
    <%= link_to root_path do%>
      <h2>Chirpy</h2>
    <% end %>

    <%= link_to dashboards_path, :class => ["nav-link", current_class?(dashboards_path)] do %>
      <p class="m-0"><i class="fa fa-solid fa-house-user mr-2"></i>Dashboard</p>
    <% end %>
    <%= link_to articles_path, :class => ["nav-link", current_class?(articles_path)] do %>
      <p class="m-0"><i class="fa fa-solid fa-newspaper mr-2"></i>Articles</p>
    <% end %>
    <%= link_to pages_support_path, :class => ["nav-link", current_class?(pages_support_path)] do %>
      <p class="m-0"><i class="fa fa-solid fa-headset mr-2"></i>Support</p>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
      <p class="m-0"><i class="fa fa-light fa-arrow-right mr-2"></i>Sign Out</p>
    <% end %>
    </div>