config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  post 'kids/:id/', to: 'kids#add', as: "add_word"
  # ask about where this route should be to avoid confusion with kids#destroy
  # need help with route - not connecting
  delete 'kids/:id/:word', to: 'kids#remove', as: "remove_word"
  devise_for :users
  root to: 'pages#home'
  get 'pages/support'
  get 'pages/privacy_policy'

  resources :dashboards, only: :index
  resources :kids do
    resources :dictionaries do
      resources :suggestions
      # might make sense to have the suggestions on the dictionary page
      # and then when selected immediately pushed into the dictionary words array
      # so i nested it here - but can be changed depending on our page layout
    end
  end
  resources :articles, only: %i[index show]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :pages, only: %i[create]
      resources :statistics, only: %i[create]
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @kids = policy_scope(Kid).order(created_at: :desc)
    @kids = current_user.kids.all
    authorize @kids
    @kid = Kid.new
    @articles = policy_scope(Article).order(created_at: :desc)
    authorize @articles
  end
end

app/views/dashboards/_articles.html.erb
<% @articles.each_with_index do |article, index| %>
  <% break if index == 3 %>
  <%= link_to article_path(article) do %>
    <div class="suggested-article">
      <div class="article-card-info ml-2">
        <h6><%= article.title %></h6>
        <p class="author-font"><em>By <%= article.author %></em></p>
        <div class="suggested-article-content">
          <%= simple_format(article.content.truncate(90, omission: ' ... (continued)')) %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/dashboards/_kids.html.erb
<% current_user.kids.each do |kid| %>
  <%= link_to kid_path(kid) do %>
    <% if kid.photo.attached? %>
      <div class="kid-card with-image" style="background-image: url('<%= cl_image_path kid.photo.key, height: 200, width: 200, crop: :limit, crop: :fill %>')">
      </div>
    <% else %>
      <div class="kid-card">
        <p><i class="fa fa-duotone fa-child"></i></p>
        <%= kid.first_name %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/dashboards/_profile_card.html.erb
<% if current_user.photo.attached? %>
  <%= cl_image_tag current_user.photo.key, height: 150, width: 150, crop: :fill, class: "profile-card-inner" %>
  <p><%= "#{current_user.first_name} #{current_user.last_name}" %>
  <p><%= "#{current_user.email}"%></p>
  <p><%= "API Token: #{current_user.authentication_token}" %></p>
  <%= link_to "Edit Profile", edit_user_registration_path(current_user), class: "btn btn-outline-secondary" %>
<% else %>
  <p><i class="fa fa-duotone fa-user"></i></p>
  <p><%= "#{current_user.first_name} #{current_user.last_name}" %>
  <p><%= "#{current_user.email}"%></p>
  <p><%= "API Token: #{current_user.authentication_token}" %></p>
  <%= link_to "Edit Profile", edit_user_registration_path(current_user), class: "btn btn-outline-secondary" %>
<% end %>

app/views/dashboards/index.html.erb
<%= render 'shared/navbar' %>
<div class="dash-cont">
  <h2 class="mt-5 ml-3 mb-4" id="header-center">Hello, <%= current_user.first_name %></h2>
  <%= render 'shared/sidebar' %>
  <div class="content row justify-content-around">
    <div class="col-lg-8">
      <div class="kid-cards d-flex align-items-center flex-wrap" id="card-center">
        <%= render 'kids', kids: @kids %>
        <div class="new-kid">
          <%= link_to "+", new_kid_path, class: "m-3 add-kid", data: {toggle: "modal", target: "#newKidModal"} %>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="profile-card white-card text-center mt-3">
        <div class="text-center mt-5">
          <%= render 'profile_card' %>
        </div>
      </div>
    </div>
    <div class="col-lg-12">
      <div class="suggested-articles mb-4 mt-5">
        <h3 class="ml-3">Suggested Articles</h3>
        <div class="d-flex flex-wrap justify-content-around articles">
          <%= render 'articles', articles: @articles %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="newKidModal" tabindex="-1" role="dialog" aria-labelledby="newKidModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'kids/new', kid: @kid %>
      </div>
    </div>
  </div>
</div>